"""second commit

Revision ID: 6b47a7387464
Revises: 7d7a37c996df
Create Date: 2026-02-13 13:00:21.954845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b47a7387464'
down_revision: Union[str, Sequence[str], None] = '7d7a37c996df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_zone',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('danger_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='all_danger_level'), nullable=True),
    sa.Column('disaster_type', sa.Enum('FLOOD', 'EARTHQUAKE', 'FIRE', 'CYCLONE', 'DROUGHT', 'LANDSLIDE', 'TORNADO', 'SINKHOLE', 'TSUNAMI', 'WILDFIRE', 'BLIZZARD', name='all_disaster_type'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='all_roles'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('safety_tip',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('disaster_type', sa.Enum('FLOOD', 'EARTHQUAKE', 'FIRE', 'CYCLONE', 'DROUGHT', 'LANDSLIDE', 'TORNADO', 'SINKHOLE', 'TSUNAMI', 'WILDFIRE', 'BLIZZARD', name='all_disaster_type'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('disaster_zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disaster_zone_id'], ['disaster_zone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sos_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('disaster_type', sa.Enum('FLOOD', 'EARTHQUAKE', 'FIRE', 'CYCLONE', 'DROUGHT', 'LANDSLIDE', 'TORNADO', 'SINKHOLE', 'TSUNAMI', 'WILDFIRE', 'BLIZZARD', name='all_disaster_type'), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=38, scale=2), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'ACCEPTED', 'REJECTED', name='all_sos_status'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('zone_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['disaster_zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sos_requests')
    op.drop_table('safety_tip')
    op.drop_table('users')
    op.drop_table('disaster_zone')
    # ### end Alembic commands ###
