CREATE TYPE all_disaster_type AS ENUM (
    'EARTHQUAKE',
    'FLOOD',
    'FIRE',
    'CYCLONE',
    'DROUGHT',
    'LANDSLIDE',
    'TORNADO',
    'SINKHOLE',
    'TSUNAMI',
    'WILDFIRE',
    'BLIZZARD'
);

CREATE TYPE all_danger_level AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH'
);

CREATE TYPE all_roles AS ENUM (
    'USER',
    'ADMIN'
);

CREATE TYPE all_sos_status AS ENUM (
    'PENDING',
    'ACCEPTED',
    'RESOLVED',
    'REJECTED'
);
