CREATE TABLE sos_requests (
    id bigserial PRIMARY KEY,
    created_at timestamp(6) default now(),
    disaster_type all_disaster_type,
    latitude numeric(38,2),
    longitude numeric(38,2),
    message varchar(255),
    status all_sos_status,
    updated_at timestamp(6) without time zone,
    zone_id integer references disaster_zone(id) on delete cascade,
    user_id integer references users(id) on delete cascade
);
